---
title: "SedimentIndices"
author: "Tommy"
date: "2024-06-11"
output: html_document
---

$$
\frac {G+R}{2}
$$
$$
\frac {B}{R}
$$
$$
\frac {G}{R}
$$
$$
\frac {R}{G}
$$
$$
\frac {IR}{G},\frac{IR}{R}
$$

$$
\frac {R}{B} + {B}
$$

$$
\frac {R}{G} + {IR}
$$

$$
\frac {ndwiG}{ndwiM}
$$

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(lubridate)
library(dplyr)
library(ggplot2)
```


```{r, include =F, warning=FALSE, echo=FALSE, results='hide'}
balule = read_csv("/Users/hydro3/Documents/R-Tommy/Kruger-National-Park-Sensors/balule.csv", col_names = FALSE)
#balule <- balule[1:19456, ]
balule.datenum <-balule%>%
    mutate(datenum = as.numeric(as_date(as_datetime(X1))))%>%
    mutate(hr=hour(as_datetime(X1))) %>%
    filter (hr<12)%>%
    filter(hr >= 2)%>%
    group_by(datenum) %>%
    summarize(MeanTurb = mean(as.numeric(X5)))

ggplot(data = balule.datenum, mapping = aes (x=as_date(datenum), y = MeanTurb))+
  geom_line()
```

```{r, include=F, warning=F, echo=F}
sedind10d = read_delim("/Users/hydro3/Documents/R-Tommy/sediment/Sediment_Indices.txt" , 
                       col_names = F)
```


```{r, include=F}
start = array(NA, dim = 132)
#end = start
start[1] = as_date("2022-08-01") #start date
for (i in c(2:132)) {
  start[i]=start[i-1]+5
}

#for (i in c(1:132)) {
#  end[i]=start[i+5]
#}

dates = data.frame(start)
balule$daterange = 0
for (i in (1:nrow(balule))) {
  test <- as_date(as_datetime(balule$X1[i]))
  for (j in 1:nrow(dates)) {
    if ((dates$start[j] == test))
      balule$daterange[i] <- j
  }
}

balule$X5 <- as.numeric(balule$X5)
balulesatday <- balule %>%
  group_by(daterange) %>%
  summarize(MeanTurb = mean(X5))


#ggplot(data = )
```

```{r, include=F}
sentinel <- read_csv("/Users/hydro3/Documents/R-Tommy/sediment/Sediment_Indices5day.txt", col_names = F)


sentinel$sensor <- NA
for (i in (1:nrow(balulesatday))) {
  sentinel$sensor[balulesatday$daterange[i]] <- balulesatday$MeanTurb[i]
}
```

```{r, warning=F, echo = F}
ggplot(data=sentinel, mapping= aes(x= sensor, y=X3) ) +
  geom_point()
X3c <- cor(sentinel$X3, sentinel$sensor, use = "complete.obs")
```

For X3, the correlation coefficient is $c=$ `r X3c`.

```{r, warning=F, echo = F}
ggplot(data=sentinel, mapping= aes(x= sensor, y=X4) ) +
  geom_point()
X4c <-cor(sentinel$X4, sentinel$sensor, use = "complete.obs")
```

For X4, the correlation coefficient is $c=$ `r X4c`.

```{r, warning=F, echo = F}
ggplot(data=sentinel, mapping= aes(x= sensor, y=X5) ) +
  geom_point()
X5c <- cor(sentinel$X5, sentinel$sensor, use = "complete.obs")
```

For X5, the correlation coefficient is $c=$ `r X5c`.

```{r, warning=F, echo = F}
ggplot(data=sentinel, mapping= aes(x= sensor, y=X6) ) +
  geom_point()
X6c <- cor(sentinel$X6, sentinel$sensor, use = "complete.obs")
```

For X6, the correlation coefficient is $c=$ `r X6c`.

```{r, warning=F, echo = F}
ggplot(data=sentinel, mapping= aes(x= sensor, y=X7) ) +
  geom_point()
X7c <- cor(sentinel$X7, sentinel$sensor, use = "complete.obs")
```

For X7, the correlation coefficient is $c=$ `r X7c`.

```{r, warning=F, echo = F}
ggplot(data=sentinel, mapping= aes(x= sensor, y=X8) ) +
  geom_point()
X8c <- cor(sentinel$X8, sentinel$sensor, use = "complete.obs")
```

For X8, the correlation coefficient is $c=$ `r X8c`.

```{r, warning=F, echo = F}
ggplot(data=sentinel, mapping= aes(x= sensor, y=X9) ) +
  geom_point()
X9c <- cor(sentinel$X9, sentinel$sensor, use = "complete.obs")
```

For X9, the correlation coefficient is $c=$ `r X9c`.

```{r, warning=F, echo = F}
ggplot(data=sentinel, mapping= aes(x= sensor, y=X10) ) +
  geom_point()
X10c <- cor(sentinel$X10, sentinel$sensor, use = "complete.obs")
```

For X10, the correlation coefficient is $c=$ `r X10c`.

```{r, warning=F, echo=F}
plot1 <- ggplot(data = sentinel, mapping=aes(x=X1, y= X3))+
  geom_point()+
  labs(x="Date", y="TSS1")

gplot1 <- ggplotGrob(plot1)

plot2 <- ggplot(data = sentinel, mapping=aes(x=X1, y= X4))+
  geom_point()+
  labs(x="Date", y="Secchi1")

gplot2 <- ggplotGrob(plot2)

plot3 <- ggplot(data = sentinel, mapping=aes(x=X1, y= X5))+
  geom_point()+
  labs(x="Date", y="TSS2")


gplot3 <- ggplotGrob(plot3)

plot4 <- ggplot(data = sentinel, mapping=aes(x=X1, y= X6))+
  geom_point()+
  labs(x="Date", y="Secchi2")

gplot4 <- ggplotGrob(plot4)

plot5 <- ggplot(data = sentinel, mapping=aes(x=X1, y= X7))+
  geom_point()+
  labs(x="Date", y="TSS3")

gplot5 <- ggplotGrob(plot5)

plot6 <- ggplot(data = sentinel, mapping=aes(x=X1, y= X8))+
  geom_point()+
  labs(x="Date", y="Secchi3")

gplot6 <- ggplotGrob(plot6)

plot7 <- ggplot(data = sentinel, mapping=aes(x=X1, y= X9))+
  geom_point()+
  labs(x="Date", y="TSS4")

gplot7 <- ggplotGrob(plot7)

plot8 <- ggplot(data = sentinel, mapping = aes(x=X1, y=X10))+
  geom_point()+ 
  labs(x="Date", y= "NDWI")

gplot8 <- ggplotGrob(plot8)


plot9 <- ggplot(data = sentinel, mapping=aes(x=X1, y= sensor))+
  geom_point()+
  labs(x="Date", y="sensor")

gplot9 <- ggplotGrob(plot9)

grid::grid.newpage()
plot10 <- grid::grid.draw(rbind(gplot1, gplot2, gplot3))

grid::grid.newpage()
plot11 <- grid::grid.draw(rbind(gplot4, gplot5, gplot6))

grid::grid.newpage()
plot12 <- grid::grid.draw(rbind(gplot7, gplot8, gplot9))
```



